### ISSUE TITLE
Make mestobo runnable from eclipse

### ISSUE THREAD

**Issue by effad** [mestobo/mestobo#1]
At the moment one has to add a VM argument like this:

--module-path /home/rli/Downloads/javafx-sdk-18.0.1/lib --add-modules javafx.controls,javafx.fxml

in order for mestobo to run from eclipse.

This should work out of the box

**Comment by patrick-peer** [comment]
I separated the main class from the JavaFX Application class, as suggested by [a post on stackoverflow](https://stackoverflow.com/a/52631238). This works for Eclipse and Indellij Idea (which had the same problem)
